INSERT INTO variety (breed_id, id, variety_name) VALUES (4, 1, 'boston');
INSERT INTO variety (breed_id, id, variety_name) VALUES (4, 2, 'french');
INSERT INTO variety (breed_id, id, variety_name) VALUES (7, 3, 'border');
INSERT INTO variety (breed_id, id, variety_name) VALUES (8, 4, 'cardigan');
INSERT INTO variety (breed_id, id, variety_name) VALUES (10, 5, 'bull');
INSERT INTO variety (breed_id, id, variety_name) VALUES (10, 6, 'tibetan');
INSERT INTO variety (breed_id, id, variety_name) VALUES (11, 7, 'giant');
INSERT INTO variety (breed_id, id, variety_name) VALUES (11, 8, 'miniature');
INSERT INTO variety (breed_id, id, variety_name) VALUES (12, 9, 'pomorski');
INSERT INTO variety (breed_id, id, variety_name) VALUES (12, 10, 'mazowiecki');
INSERT INTO variety (breed_id, id, variety_name) VALUES (13, 11, 'nadmorski');
INSERT INTO variety (breed_id, id, variety_name) VALUES (13, 12, 'nizinny');
INSERT INTO variety (breed_id, id, variety_name) VALUES (13, 13, 'wyżynny');
INSERT INTO breed (id, breed_name) VALUES (1, 'affenpinscher');
INSERT INTO breed (id, breed_name) VALUES (2, 'beagle');
INSERT INTO breed (id, breed_name) VALUES (3, 'boxer');
INSERT INTO breed (id, breed_name) VALUES (4, 'bulldog');
INSERT INTO breed (id, breed_name) VALUES (5, 'bull terrier');
INSERT INTO breed (id, breed_name) VALUES (6, 'chihuahua');
INSERT INTO breed (id, breed_name) VALUES (7, 'collie');
INSERT INTO breed (id, breed_name) VALUES (8, 'corgi');
INSERT INTO breed (id, breed_name) VALUES (9, 'dingo');
INSERT INTO breed (id, breed_name) VALUES (10, 'mastiff');
INSERT INTO breed (id, breed_name) VALUES (11, 'schnauzer');
INSERT INTO breed (id, breed_name) VALUES (12, 'wilczur');
INSERT INTO breed (id, breed_name) VALUES (13, 'jamnior');
INSERT INTO breed (id, breed_name) VALUES (14, 'lucek');